---
version: "3"

vars:
  # add variables here
  {}

dotenv: [".config.env"]

env:
  # add env variables
  {}

includes:
  ansible: .taskfiles/AnsibleTasks.yml
  vagrant: .taskfiles/VagrantTasks.yml

tasks:

  init:
    desc: Initialize workstation dependencies with Brew
    cmds:
      - brew install {{.DEPS}} {{.CLI_ARGS}}
    preconditions:
      - sh: command -v brew
        msg: |
          Homebrew is not installed. Using MacOS, Linux or WSL?
          Head over to https://brew.sh to get up and running.
    vars:
      DEPS: >-
        age
        ansible
        direnv
        go-task/tap/go-task
        jq
        pre-commit
        sops
        yamllint
        yq
        vagrant