---
version: "3"

vars:
  # add variables here
  {}

dotenv: [".config.env"]

env:
  EDITOR: nano

includes:
  ansible: .taskfiles/AnsibleTasks.yml
  vagrant: .taskfiles/VagrantTasks.yml
  prom: .taskfiles/PrometheusTasks.yml

tasks:

  init:
    desc: Initialize workstation dependencies with Brew
    cmds:
      - brew install {{.DEPS}} {{.CLI_ARGS}}
    preconditions:
      - sh: command -v brew
        msg: |
          Homebrew is not installed. Using MacOS, Linux or WSL?
          Head over to https://brew.sh to get up and running.
    vars:
      DEPS: >-
        ansible
        direnv
        go-task/tap/go-task
        jq
        yamllint
        vagrant

  stack-up:
    desc: builds the whole development stack
    cmds:
      - task: vagrant:up
      - task: ansible:comcheck
      - task: ansible:up